import createError from "../utils/createError"

export const createMessage = async (req, res, next)=>{
    try {
        
    } catch (err) {
        next(err)
    }
}
